<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>Intersection.CurveCurve Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="CurveCurve method" /><meta name="System.Keywords" content="Intersection.CurveCurve method" /><meta name="Microsoft.Help.F1" content="Rhino.Geometry.Intersect.Intersection.CurveCurve" /><meta name="Microsoft.Help.Id" content="M:Rhino.Geometry.Intersect.Intersection.CurveCurve(Rhino.Geometry.Curve,Rhino.Geometry.Curve,System.Double,System.Double)" /><meta name="Description" content="Finds the intersections between two curves." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Geometry.Intersect" /><meta name="file" content="878F02C7" /><meta name="guid" content="878F02C7" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon SDK<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="A7FBC69C.htm" title="RhinoCommon SDK" tocid="roottoc">RhinoCommon SDK</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="8B841011.htm" title="Rhino.Geometry.Intersect" tocid="8B841011">Rhino.Geometry.Intersect</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="6387F80E.htm" title="Intersection Class" tocid="6387F80E">Intersection Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="CA26C0BA.htm" title="Intersection Methods" tocid="CA26C0BA">Intersection Methods</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="35757663.htm" title="BrepBrep Method " tocid="35757663">BrepBrep Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="7ABA58D6.htm" title="BrepPlane Method " tocid="7ABA58D6">BrepPlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="6008E98B.htm" title="BrepSurface Method " tocid="6008E98B">BrepSurface Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="EAAC8445.htm" title="CurveBrep Method " tocid="EAAC8445">CurveBrep Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="8E6DB050.htm" title="CurveBrepFace Method " tocid="8E6DB050">CurveBrepFace Method </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="878F02C7.htm" title="CurveCurve Method " tocid="878F02C7">CurveCurve Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="C786D206.htm" title="CurvePlane Method " tocid="C786D206">CurvePlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="A3BFF41E.htm" title="CurveSelf Method " tocid="A3BFF41E">CurveSelf Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="EDC4A49C.htm" title="CurveSurface Method " tocid="EDC4A49C">CurveSurface Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="9E253CD.htm" title="LineBox Method " tocid="9E253CD">LineBox Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="77226FAB.htm" title="LineCircle Method " tocid="77226FAB">LineCircle Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="8AD8009F.htm" title="LineCylinder Method " tocid="8AD8009F">LineCylinder Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="341BB52.htm" title="LineLine Method " tocid="341BB52">LineLine Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="69F20783.htm" title="LinePlane Method " tocid="69F20783">LinePlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="48D375FA.htm" title="LineSphere Method " tocid="48D375FA">LineSphere Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="52FE0172.htm" title="MeshLine Method " tocid="52FE0172">MeshLine Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="8D14EE85.htm" title="MeshMeshAccurate Method " tocid="8D14EE85">MeshMeshAccurate Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="B949ACCF.htm" title="MeshMeshFast Method " tocid="B949ACCF">MeshMeshFast Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="6D477337.htm" title="MeshPlane Method " tocid="6D477337">MeshPlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="EC7911F8.htm" title="MeshPolyline Method " tocid="EC7911F8">MeshPolyline Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="78BAE6F7.htm" title="MeshRay Method " tocid="78BAE6F7">MeshRay Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="11623FB.htm" title="PlaneCircle Method " tocid="11623FB">PlaneCircle Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="DF488B4B.htm" title="PlanePlane Method " tocid="DF488B4B">PlanePlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="D99070E9.htm" title="PlanePlanePlane Method " tocid="D99070E9">PlanePlanePlane Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="E84031D8.htm" title="PlaneSphere Method " tocid="E84031D8">PlaneSphere Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="4478E1AE.htm" title="ProjectPointsToBreps Method " tocid="4478E1AE">ProjectPointsToBreps Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="92ADE341.htm" title="ProjectPointsToBrepsEx Method " tocid="92ADE341">ProjectPointsToBrepsEx Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="D1A8E39B.htm" title="ProjectPointsToMeshes Method " tocid="D1A8E39B">ProjectPointsToMeshes Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="2FA2E99C.htm" title="ProjectPointsToMeshesEx Method " tocid="2FA2E99C">ProjectPointsToMeshesEx Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="67D145EA.htm" title="RayShoot Method " tocid="67D145EA">RayShoot Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="AA9CD443.htm" title="SphereSphere Method " tocid="AA9CD443">SphereSphere Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="B699528F.htm" title="SurfaceSurface Method " tocid="B699528F">SurfaceSurface Method </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn">Intersection<span id="LST20A0F900_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST20A0F900_0?cpp=::|nu=.");</script>CurveCurve Method </td></tr></table><span class="introStyle">Rhino for Mac 5.1</span><div class="summary">
            Finds the intersections between two curves.
            </div><p> </p><strong>Namespace:</strong> <a href="8B841011.htm">Rhino.Geometry.Intersect</a><br /><strong>Assembly:</strong> RhinoCommon (in RhinoCommon.dll) Version: 5.1.50000.0 (5.0.20693.0)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="keyword">static</span> <span class="identifier">CurveIntersections</span> <span class="identifier">CurveCurve</span>(
	<span class="identifier">Curve</span> <span class="parameter">curveA</span>,
	<span class="identifier">Curve</span> <span class="parameter">curveB</span>,
	<span class="identifier">double</span> <span class="parameter">tolerance</span>,
	<span class="identifier">double</span> <span class="parameter">overlapTolerance</span>
)</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Shared</span> <span class="keyword">Function</span> <span class="identifier">CurveCurve</span> ( 
	<span class="parameter">curveA</span> <span class="keyword">As</span> <span class="identifier">Curve</span>,
	<span class="parameter">curveB</span> <span class="keyword">As</span> <span class="identifier">Curve</span>,
	<span class="parameter">tolerance</span> <span class="keyword">As</span> <span class="identifier">Double</span>,
	<span class="parameter">overlapTolerance</span> <span class="keyword">As</span> <span class="identifier">Double</span>
) <span class="keyword">As</span> <span class="identifier">CurveIntersections</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Parameters</h4><dl><dt><span class="parameter">curveA</span></dt><dd>Type: <a href="4D62EF95.htm">Rhino.Geometry<span id="LST20A0F900_1"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST20A0F900_1?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Curve</a><br />First curve for intersection.</dd><dt><span class="parameter">curveB</span></dt><dd>Type: <a href="4D62EF95.htm">Rhino.Geometry<span id="LST20A0F900_2"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST20A0F900_2?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Curve</a><br />Second curve for intersection.</dd><dt><span class="parameter">tolerance</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span id="LST20A0F900_3"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST20A0F900_3?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Double</a><br />Intersection tolerance. If the curves approach each other to within tolerance,
            an intersection is assumed.</dd><dt><span class="parameter">overlapTolerance</span></dt><dd>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">System<span id="LST20A0F900_4"></span><script type="text/javascript">AddLanguageSpecificTextSet("LST20A0F900_4?cs=.|vb=.|cpp=::|nu=.|fs=.");</script>Double</a><br />The tolerance with which the curves are tested.</dd></dl><h4 class="subHeading">Return Value</h4>Type: <a href="DE547734.htm">CurveIntersections</a><br />A collection of intersection events.</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBABA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','cs','1','2');return false;">C#</a></div><div id="ID0EBBABA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBBABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">partial</span> <span class="highlight-keyword">class</span> Examples
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">static</span> Rhino.Commands.Result IntersectCurves(Rhino.RhinoDoc doc)
  {
    <span class="highlight-comment">// Select two curves to intersect</span>
    <span class="highlight-keyword">var</span> go = <span class="highlight-keyword">new</span> Rhino.Input.Custom.GetObject();
    go.SetCommandPrompt(<span class="highlight-literal">"Select two curves"</span>);
    go.GeometryFilter = Rhino.DocObjects.ObjectType.Curve;
    go.GetMultiple(<span class="highlight-number">2</span>, <span class="highlight-number">2</span>);
    <span class="highlight-keyword">if</span> (go.CommandResult() != Rhino.Commands.Result.Success)
      <span class="highlight-keyword">return</span> go.CommandResult();

    <span class="highlight-comment">// Validate input</span>
    <span class="highlight-keyword">var</span> curveA = go.Object(<span class="highlight-number">0</span>).Curve();
    <span class="highlight-keyword">var</span> curveB = go.Object(<span class="highlight-number">1</span>).Curve();
    <span class="highlight-keyword">if</span> (curveA == <span class="highlight-keyword">null</span> || curveB == <span class="highlight-keyword">null</span>)
      <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure;

    <span class="highlight-comment">// Calculate the intersection</span>
    <span class="highlight-keyword">const</span> <span class="highlight-keyword">double</span> intersection_tolerance = <span class="highlight-number">0.001</span>;
    <span class="highlight-keyword">const</span> <span class="highlight-keyword">double</span> overlap_tolerance = <span class="highlight-number">0.0</span>;
    <span class="highlight-keyword">var</span> events = Rhino.Geometry.Intersect.Intersection.CurveCurve(curveA, curveB, intersection_tolerance, overlap_tolerance);

    <span class="highlight-comment">// Process the results</span>
    <span class="highlight-keyword">if</span> (events != <span class="highlight-keyword">null</span>)
    {
      <span class="highlight-keyword">for</span> (<span class="highlight-keyword">int</span> i = <span class="highlight-number">0</span>; i &lt; events.Count; i++)
      {
        <span class="highlight-keyword">var</span> ccx_event = events[i];
        doc.Objects.AddPoint(ccx_event.PointA);
        <span class="highlight-keyword">if</span> (ccx_event.PointA.DistanceTo(ccx_event.PointB) &gt; <span class="highlight-keyword">double</span>.Epsilon)
        {
          doc.Objects.AddPoint(ccx_event.PointB);
          doc.Objects.AddLine(ccx_event.PointA, ccx_event.PointB);
        }
      }
      doc.Views.Redraw();
    }
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success;
  }
}</pre></div><div id="ID0EBBABA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Partial</span> <span class="highlight-keyword">Class</span> Examples
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Shared</span> <span class="highlight-keyword">Function</span> IntersectCurves(doc <span class="highlight-keyword">As</span> Rhino.RhinoDoc) <span class="highlight-keyword">As</span> Rhino.Commands.Result
    <span class="highlight-comment">' Select two curves to intersect</span>
    <span class="highlight-keyword">Dim</span> go = <span class="highlight-keyword">New</span> Rhino.Input.Custom.GetObject()
    go.SetCommandPrompt(<span class="highlight-literal">"Select two curves"</span>)
    go.GeometryFilter = Rhino.DocObjects.ObjectType.Curve
    go.GetMultiple(<span class="highlight-number">2</span>, <span class="highlight-number">2</span>)
    <span class="highlight-keyword">If</span> go.CommandResult() &lt;&gt; Rhino.Commands.Result.Success <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> go.CommandResult()
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-comment">' Validate input</span>
    <span class="highlight-keyword">Dim</span> curveA = go.[<span class="highlight-keyword">Object</span>](<span class="highlight-number">0</span>).Curve()
    <span class="highlight-keyword">Dim</span> curveB = go.[<span class="highlight-keyword">Object</span>](<span class="highlight-number">1</span>).Curve()
    <span class="highlight-keyword">If</span> curveA <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">OrElse</span> curveB <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Failure
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-comment">' Calculate the intersection</span>
    <span class="highlight-keyword">Const</span> intersection_tolerance <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-number">0.001</span>
    <span class="highlight-keyword">Const</span> overlap_tolerance <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-number">0.0</span>
    <span class="highlight-keyword">Dim</span> events = Rhino.Geometry.Intersect.Intersection.CurveCurve(curveA, curveB, intersection_tolerance, overlap_tolerance)

    <span class="highlight-comment">' Process the results</span>
    <span class="highlight-keyword">If</span> events <span class="highlight-keyword">IsNot</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">For</span> i <span class="highlight-keyword">As</span> <span class="highlight-keyword">Integer</span> = <span class="highlight-number">0</span> <span class="highlight-keyword">To</span> events.Count - <span class="highlight-number">1</span>
        <span class="highlight-keyword">Dim</span> ccx_event = events(i)
        doc.Objects.AddPoint(ccx_event.PointA)
        <span class="highlight-keyword">If</span> ccx_event.PointA.DistanceTo(ccx_event.PointB) &gt; <span class="highlight-keyword">Double</span>.Epsilon <span class="highlight-keyword">Then</span>
          doc.Objects.AddPoint(ccx_event.PointB)
          doc.Objects.AddLine(ccx_event.PointA, ccx_event.PointB)
        <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
      <span class="highlight-keyword">Next</span>
      doc.Views.Redraw()
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Success
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBABA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EAAABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">import</span> scriptcontext

<span class="highlight-keyword">def</span> IntersectCurves():
    <span class="highlight-comment"># Select two curves to intersect</span>
    go = Rhino.Input.Custom.GetObject()
    go.SetCommandPrompt(<span class="highlight-literal">"Select two curves"</span>)
    go.GeometryFilter = Rhino.DocObjects.ObjectType.Curve
    go.GetMultiple(<span class="highlight-number">2</span>, <span class="highlight-number">2</span>)
    <span class="highlight-keyword">if</span> go.CommandResult()!=Rhino.Commands.Result.Success: <span class="highlight-keyword">return</span>

    <span class="highlight-comment"># Validate input</span>
    curveA = go.Object(<span class="highlight-number">0</span>).Curve()
    curveB = go.Object(<span class="highlight-number">1</span>).Curve()
    <span class="highlight-keyword">if</span> <span class="highlight-keyword">not</span> curveA <span class="highlight-keyword">or</span> <span class="highlight-keyword">not</span> curveB: <span class="highlight-keyword">return</span>

    <span class="highlight-comment"># Calculate the intersection</span>
    intersection_tolerance = <span class="highlight-number">0.001</span>
    overlap_tolerance = <span class="highlight-number">0.0</span>
    events = Rhino.Geometry.Intersect.Intersection.CurveCurve(curveA, curveB, intersection_tolerance, overlap_tolerance)

    <span class="highlight-comment"># Process the results</span>
    <span class="highlight-keyword">if</span> <span class="highlight-keyword">not</span> events: <span class="highlight-keyword">return</span>
    <span class="highlight-keyword">for</span> ccx_event <span class="highlight-keyword">in</span> events:
        scriptcontext.doc.Objects.AddPoint(ccx_event.PointA)
        <span class="highlight-keyword">if</span> ccx_event.PointA.DistanceTo(ccx_event.PointB) &gt; float.Epsilon:
            scriptcontext.doc.Objects.AddPoint(ccx_event.PointB)
            scriptcontext.doc.Objects.AddLine(ccx_event.PointA, ccx_event.PointB)
    scriptcontext.doc.Views.Redraw()

<span class="highlight-keyword">if</span> __name__==<span class="highlight-literal">"__main__"</span>:
    IntersectCurves()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAABA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="6387F80E.htm">Intersection Class</a></div><div class="seeAlsoStyle"><a href="8B841011.htm">Rhino.Geometry.Intersect Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Updated 4 October 2015 - Robert McNeel and Associates<p><a href="http://discourse.mcneel.com/" target="_blank">Report wishes and bugs: http://discourse.mcneel.com/</a></p><div class="feedbackLink">Send comments on this topic to
        <a id="HT_MailLink" href="mailto:steve%40mcneel.com?Subject=RhinoCommon SDK">steve@mcneel.com</a></div><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title + "\u0026body=" + encodeURIComponent("Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed.");
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script> </div></body></html>