<html><head><meta http-equiv="X-UA-Compatible" content="IE=edge" /><link rel="shortcut icon" href="../icons/favicon.ico" /><link rel="stylesheet" type="text/css" href="../styles/branding.css" /><link rel="stylesheet" type="text/css" href="../styles/branding-en-US.css" /><script type="text/javascript" src="../scripts/branding.js"> </script><meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /><title>GetBaseClass.Number Method </title><meta name="Language" content="en-us" /><meta name="System.Keywords" content="Number method" /><meta name="System.Keywords" content="GetBaseClass.Number method" /><meta name="Microsoft.Help.F1" content="Rhino.Input.Custom.GetBaseClass.Number" /><meta name="Microsoft.Help.Id" content="M:Rhino.Input.Custom.GetBaseClass.Number" /><meta name="Description" content="Gets a number if GetPoint.Get(), GetObject.GetObjects(), etc., returns GetResult.Number." /><meta name="Microsoft.Help.ContentType" content="Reference" /><meta name="BrandingAware" content="true" /><meta name="container" content="Rhino.Input.Custom" /><meta name="file" content="E886F144" /><meta name="guid" content="E886F144" /><link type="text/css" rel="stylesheet" href="../styles/highlight.css" /><script type="text/javascript" src="../scripts/highlight.js"> </script><link rel="stylesheet" type="text/css" href="../styles/branding-Website.css" /><script type="text/javascript" src="../scripts/jquery-1.11.0.min.js"></script><script type="text/javascript" src="../scripts/branding-Website.js"></script></head><body onload="OnLoad('cs')"><input type="hidden" id="userDataCache" class="userDataStyle" /><div class="pageHeader" id="PageHeader">RhinoCommon SDK<form id="SearchForm" method="get" action="#" onsubmit="javascript:TransferToSearchPage(); return false;"><input id="SearchTextBox" type="text" maxlength="200" /><button id="SearchButton" type="submit"></button></form></div><div class="pageBody"><div class="leftNav" id="leftNav"><div id="tocNav"><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="A7FBC69C.htm" title="RhinoCommon SDK" tocid="roottoc">RhinoCommon SDK</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="185500F3.htm" title="Rhino.Input.Custom" tocid="185500F3">Rhino.Input.Custom</a></div><div class="toclevel0" data-toclevel="0"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="C3F3325A.htm" title="GetBaseClass Class" tocid="C3F3325A">GetBaseClass Class</a></div><div class="toclevel1" data-toclevel="1" data-childrenloaded="true"><a class="tocExpanded" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="5A1B30BE.htm" title="GetBaseClass Methods" tocid="5A1B30BE">GetBaseClass Methods</a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="BF7B858C.htm" title="AcceptColor Method " tocid="BF7B858C">AcceptColor Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="82341C55.htm" title="AcceptCustomMessage Method " tocid="82341C55">AcceptCustomMessage Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="23EE9DE2.htm" title="AcceptNothing Method " tocid="23EE9DE2">AcceptNothing Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="DB0F87EC.htm" title="AcceptNumber Method " tocid="DB0F87EC">AcceptNumber Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="1CD3E1A1.htm" title="AcceptPoint Method " tocid="1CD3E1A1">AcceptPoint Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="EE4F85F8.htm" title="AcceptString Method " tocid="EE4F85F8">AcceptString Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="7112E36D.htm" title="AcceptUndo Method " tocid="7112E36D">AcceptUndo Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="EA494A28.htm" title="AddOption Method " tocid="EA494A28">AddOption Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="4479838B.htm" title="AddOptionColor Method " tocid="4479838B">AddOptionColor Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="E42F66F3.htm" title="AddOptionDouble Method " tocid="E42F66F3">AddOptionDouble Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="265D0CC7.htm" title="AddOptionEnumList(T) Method " tocid="265D0CC7">AddOptionEnumList(T) Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="42428547.htm" title="AddOptionEnumSelectionList(T) Method " tocid="42428547">AddOptionEnumSelectionList(T) Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="FB4E06FE.htm" title="AddOptionInteger Method " tocid="FB4E06FE">AddOptionInteger Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="F3ECF2E8.htm" title="AddOptionList Method " tocid="F3ECF2E8">AddOptionList Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="6B341718.htm" title="AddOptionToggle Method " tocid="6B341718">AddOptionToggle Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="663D5B97.htm" title="ClearCommandOptions Method " tocid="663D5B97">ClearCommandOptions Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="3D4BA2D7.htm" title="ClearDefault Method " tocid="3D4BA2D7">ClearDefault Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="964B26C0.htm" title="Color Method " tocid="964B26C0">Color Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="A73F74D7.htm" title="CommandResult Method " tocid="A73F74D7">CommandResult Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="41D01489.htm" title="CustomMessage Method " tocid="41D01489">CustomMessage Method </a></div><div class="toclevel2" data-toclevel="2"><a class="tocCollapsed" onclick="javascript: Toggle(this);" href="#!" /><a data-tochassubtree="true" href="28F6C067.htm" title="Dispose Method " tocid="28F6C067">Dispose Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="9A464246.htm" title="EnableTransparentCommands Method " tocid="9A464246">EnableTransparentCommands Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="6A092437.htm" title="Finalize Method " tocid="6A092437">Finalize Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="1CCEE6A7.htm" title="GetSelectedEnumValue(T) Method " tocid="1CCEE6A7">GetSelectedEnumValue(T) Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="83E31653.htm" title="GetSelectedEnumValueFromSelectionList(T) Method " tocid="83E31653">GetSelectedEnumValueFromSelectionList(T) Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="78DB8E52.htm" title="GotDefault Method " tocid="78DB8E52">GotDefault Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="572A64F5.htm" title="Line2d Method " tocid="572A64F5">Line2d Method </a></div><div class="toclevel2 current" data-toclevel="2"><a data-tochassubtree="false" href="E886F144.htm" title="Number Method " tocid="E886F144">Number Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="F3A725EC.htm" title="Option Method " tocid="F3A725EC">Option Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="A3A555A8.htm" title="OptionIndex Method " tocid="A3A555A8">OptionIndex Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="AE9EED81.htm" title="PickRectangle Method " tocid="AE9EED81">PickRectangle Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="F3A3FAB5.htm" title="Point Method " tocid="F3A3FAB5">Point Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="A36E8AF3.htm" title="Point2d Method " tocid="A36E8AF3">Point2d Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="110943A9.htm" title="PostCustomMessage Method " tocid="110943A9">PostCustomMessage Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="ED541420.htm" title="Rectangle2d Method " tocid="ED541420">Rectangle2d Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="B3A1BB04.htm" title="Result Method " tocid="B3A1BB04">Result Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="CC32E5C2.htm" title="SetCommandPrompt Method " tocid="CC32E5C2">SetCommandPrompt Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="37FCB67B.htm" title="SetCommandPromptDefault Method " tocid="37FCB67B">SetCommandPromptDefault Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="33BA2C5D.htm" title="SetDefaultColor Method " tocid="33BA2C5D">SetDefaultColor Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="EEB813C2.htm" title="SetDefaultInteger Method " tocid="EEB813C2">SetDefaultInteger Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="17AFB683.htm" title="SetDefaultNumber Method " tocid="17AFB683">SetDefaultNumber Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="91131812.htm" title="SetDefaultPoint Method " tocid="91131812">SetDefaultPoint Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="C0C63989.htm" title="SetDefaultString Method " tocid="C0C63989">SetDefaultString Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="23BBA.htm" title="SetWaitDuration Method " tocid="23BBA">SetWaitDuration Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="F5A134F5.htm" title="StringResult Method " tocid="F5A134F5">StringResult Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="AB37B416.htm" title="Vector Method " tocid="AB37B416">Vector Method </a></div><div class="toclevel2" data-toclevel="2"><a data-tochassubtree="false" href="81B9A944.htm" title="View Method " tocid="81B9A944">View Method </a></div></div><div id="tocResizableEW" onmousedown="OnMouseDown(event);"></div><div id="TocResize" class="tocResize"><img id="ResizeImageIncrease" src="../icons/TocOpen.gif" onclick="OnIncreaseToc()" alt="Click or drag to resize" title="Click or drag to resize" /><img id="ResizeImageReset" src="../icons/TocClose.gif" style="display:none" onclick="OnResetToc()" alt="Click or drag to resize" title="Click or drag to resize" /></div></div><div class="topicContent" id="TopicContent"><table class="titleTable"><tr><td class="titleColumn">GetBaseClass<span id="LSTE886F144_0"></span><script type="text/javascript">AddLanguageSpecificTextSet("LSTE886F144_0?cpp=::|nu=.");</script>Number Method </td></tr></table><span class="introStyle">Rhino for Mac 5.1</span><div class="summary">
            Gets a number if GetPoint.Get(), GetObject.GetObjects(), etc., returns GetResult.Number.
            </div><p> </p><strong>Namespace:</strong> <a href="185500F3.htm">Rhino.Input.Custom</a><br /><strong>Assembly:</strong> RhinoCommon (in RhinoCommon.dll) Version: 5.1.50000.0 (5.0.20693.0)<div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID1RB')" onkeypress="SectionExpandCollapse_CheckKey('ID1RB', event)" tabindex="0"><img id="ID1RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Syntax</span></div><div id="ID1RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBCA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','cs','1','2');return false;">C#</a></div><div id="ID0EBCA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBCA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBCA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBCA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBCA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="keyword">public</span> <span class="identifier">double</span> <span class="identifier">Number</span>()</pre></div><div id="ID0EBCA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="keyword">Public</span> <span class="keyword">Function</span> <span class="identifier">Number</span> <span class="keyword">As</span> <span class="identifier">Double</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBCA");</script><h4 class="subHeading">Return Value</h4>Type: <a href="http://msdn2.microsoft.com/en-us/library/643eft0t" target="_blank">Double</a><br />The number chosen by the user.</div><div class="collapsibleAreaRegion"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID2RB')" onkeypress="SectionExpandCollapse_CheckKey('ID2RB', event)" tabindex="0"><img id="ID2RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />Examples</span></div><div id="ID2RBSection" class="collapsibleSection"><div class="codeSnippetContainer"><div class="codeSnippetContainerTabs"><div id="ID0EBBABA_tab1" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','cs','1','2');return false;">C#</a></div><div id="ID0EBBABA_tab2" class="codeSnippetContainerTab"><a href="#" onclick="javascript:ChangeTab('ID0EBBABA','vb','2','2');return false;">VB</a></div></div><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EBBABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EBBABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EBBABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">using</span> System;

<span class="highlight-keyword">partial</span> <span class="highlight-keyword">class</span> Examples
{
  <span class="highlight-keyword">public</span> <span class="highlight-keyword">static</span> Rhino.Commands.Result AddBackgroundBitmap(Rhino.RhinoDoc doc)
  {
    <span class="highlight-comment">// Allow the user to select a bitmap file</span>
    <span class="highlight-keyword">var</span> fd = <span class="highlight-keyword">new</span> Rhino.UI.OpenFileDialog { Filter = <span class="highlight-literal">"Image Files (*.bmp;*.png;*.jpg)|*.bmp;*.png;*.jpg"</span> };
      <span class="highlight-keyword">if</span> (!fd.ShowDialog())
      <span class="highlight-keyword">return</span> Rhino.Commands.Result.Cancel;

    <span class="highlight-comment">// Verify the file that was selected</span>
    System.Drawing.Image image;
    <span class="highlight-keyword">try</span>
    {
      image = System.Drawing.Image.FromFile(fd.FileName);
    }
    <span class="highlight-keyword">catch</span> (Exception)
    {
      <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure;
    }

    <span class="highlight-comment">// Allow the user to pick the bitmap origin</span>
    <span class="highlight-keyword">var</span> gp = <span class="highlight-keyword">new</span> Rhino.Input.Custom.GetPoint();
    gp.SetCommandPrompt(<span class="highlight-literal">"Bitmap Origin"</span>);
    gp.ConstrainToConstructionPlane(<span class="highlight-keyword">true</span>);
    gp.Get();
    <span class="highlight-keyword">if</span> (gp.CommandResult() != Rhino.Commands.Result.Success)
      <span class="highlight-keyword">return</span> gp.CommandResult();

    <span class="highlight-comment">// Get the view that the point was picked in.</span>
    <span class="highlight-comment">// This will be the view that the bitmap appears in.</span>
    <span class="highlight-keyword">var</span> view = gp.View();
    <span class="highlight-keyword">if</span> (view == <span class="highlight-keyword">null</span>)
    {
      view = doc.Views.ActiveView;
      <span class="highlight-keyword">if</span> (view == <span class="highlight-keyword">null</span>)
        <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure;
    }

    <span class="highlight-comment">// Allow the user to specify the bitmap width in model units</span>
    <span class="highlight-keyword">var</span> gn = <span class="highlight-keyword">new</span> Rhino.Input.Custom.GetNumber();
    gn.SetCommandPrompt(<span class="highlight-literal">"Bitmap width"</span>);
    gn.SetLowerLimit(<span class="highlight-number">1.0</span>, <span class="highlight-keyword">false</span>);
    gn.Get();
    <span class="highlight-keyword">if</span> (gn.CommandResult() != Rhino.Commands.Result.Success)
      <span class="highlight-keyword">return</span> gn.CommandResult();

    <span class="highlight-comment">// Cook up some scale factors</span>
    <span class="highlight-keyword">var</span> w = gn.Number();
    <span class="highlight-keyword">var</span> image_width = image.Width;
    <span class="highlight-keyword">var</span> image_height = image.Height;
    <span class="highlight-keyword">var</span> h = w * (image_height / image_width);

    <span class="highlight-keyword">var</span> plane = view.ActiveViewport.ConstructionPlane();
    plane.Origin = gp.Point();
    view.ActiveViewport.SetTraceImage(fd.FileName, plane, w, h, <span class="highlight-keyword">false</span>, <span class="highlight-keyword">false</span>);
    view.Redraw();
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success;
  }
}</pre></div><div id="ID0EBBABA_code_Div2" class="codeSnippetContainerCode" style="display: none"><pre xml:space="preserve"><span class="highlight-keyword">Partial</span> <span class="highlight-keyword">Class</span> Examples
  <span class="highlight-keyword">Public</span> <span class="highlight-keyword">Shared</span> <span class="highlight-keyword">Function</span> AddBackgroundBitmap(<span class="highlight-keyword">ByVal</span> doc <span class="highlight-keyword">As</span> Rhino.RhinoDoc) <span class="highlight-keyword">As</span> Rhino.Commands.Result
    <span class="highlight-comment">' Allow the user to select a bitmap file</span>
    <span class="highlight-keyword">Dim</span> fd <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Rhino.UI.OpenFileDialog()
    fd.Filter = <span class="highlight-literal">"Image Files (*.bmp;*.png;*.jpg)|*.bmp;*.png;*.jpg"</span>
    <span class="highlight-keyword">If</span> fd.ShowDialog() &lt;&gt; System.Windows.Forms.DialogResult.OK <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Cancel
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-comment">' Verify the file that was selected</span>
    <span class="highlight-keyword">Dim</span> image <span class="highlight-keyword">As</span> System.Drawing.Image
    <span class="highlight-keyword">Try</span>
      image = System.Drawing.Image.FromFile(fd.FileName)
    <span class="highlight-keyword">Catch</span> generatedExceptionName <span class="highlight-keyword">As</span> Exception
      <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Failure
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">Try</span>

    <span class="highlight-comment">' Allow the user to pick the bitmap origin</span>
    <span class="highlight-keyword">Dim</span> gp <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Rhino.Input.Custom.GetPoint()
    gp.SetCommandPrompt(<span class="highlight-literal">"Bitmap Origin"</span>)
    gp.ConstrainToConstructionPlane(<span class="highlight-keyword">True</span>)
    gp.<span class="highlight-keyword">Get</span>()
    <span class="highlight-keyword">If</span> gp.CommandResult() &lt;&gt; Rhino.Commands.Result.Success <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> gp.CommandResult()
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-comment">' Get the view that the point was picked in.</span>
    <span class="highlight-comment">' This will be the view that the bitmap appears in.</span>
    <span class="highlight-keyword">Dim</span> view <span class="highlight-keyword">As</span> Rhino.Display.RhinoView = gp.View()
    <span class="highlight-keyword">If</span> view <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
      view = doc.Views.ActiveView
      <span class="highlight-keyword">If</span> view <span class="highlight-keyword">Is</span> <span class="highlight-keyword">Nothing</span> <span class="highlight-keyword">Then</span>
        <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Failure
      <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-comment">' Allow the user to specify the bitmap with in model units</span>
    <span class="highlight-keyword">Dim</span> gn <span class="highlight-keyword">As</span> <span class="highlight-keyword">New</span> Rhino.Input.Custom.GetNumber()
    gn.SetCommandPrompt(<span class="highlight-literal">"Bitmap width"</span>)
    gn.SetLowerLimit(<span class="highlight-number">1.0</span>, <span class="highlight-keyword">False</span>)
    gn.<span class="highlight-keyword">Get</span>()
    <span class="highlight-keyword">If</span> gn.CommandResult() &lt;&gt; Rhino.Commands.Result.Success <span class="highlight-keyword">Then</span>
      <span class="highlight-keyword">Return</span> gn.CommandResult()
    <span class="highlight-keyword">End</span> <span class="highlight-keyword">If</span>

    <span class="highlight-comment">' Cook up some scale factors</span>
    <span class="highlight-keyword">Dim</span> w <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = gn.Number()
    <span class="highlight-keyword">Dim</span> image_width <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-keyword">CDbl</span>(image.Width)
    <span class="highlight-keyword">Dim</span> image_height <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = <span class="highlight-keyword">CDbl</span>(image.Height)
    <span class="highlight-keyword">Dim</span> h <span class="highlight-keyword">As</span> <span class="highlight-keyword">Double</span> = w * (image_height / image_width)

    <span class="highlight-keyword">Dim</span> plane <span class="highlight-keyword">As</span> Rhino.Geometry.Plane = view.ActiveViewport.ConstructionPlane()
    plane.Origin = gp.Point()
    view.ActiveViewport.SetTraceImage(fd.FileName, plane, w, h, <span class="highlight-keyword">False</span>, <span class="highlight-keyword">False</span>)
    view.Redraw()
    <span class="highlight-keyword">Return</span> Rhino.Commands.Result.Success
  <span class="highlight-keyword">End</span> <span class="highlight-keyword">Function</span>
<span class="highlight-keyword">End</span> <span class="highlight-keyword">Class</span></pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EBBABA");</script><div class="codeSnippetContainer"><div class="codeSnippetContainerCodeContainer"><div class="codeSnippetToolBar"><div class="codeSnippetToolBarText"><a id="ID0EAAABA_copyCode" href="#" onclick="javascript:CopyToClipboard('ID0EAAABA');return false;" title="Copy">Copy</a></div></div><div id="ID0EAAABA_code_Div1" class="codeSnippetContainerCode" style="display: block"><pre xml:space="preserve"><span class="highlight-keyword">import</span> Rhino
<span class="highlight-keyword">import</span> scriptcontext
<span class="highlight-keyword">import</span> System.Windows.Forms.DialogResult
<span class="highlight-keyword">import</span> System.Drawing.Image

<span class="highlight-keyword">def</span> AddBackgroundBitmap():
    <span class="highlight-comment"># Allow the user to select a bitmap file</span>
    fd = Rhino.UI.OpenFileDialog()
    fd.Filter = <span class="highlight-literal">"Image Files (*.bmp;*.png;*.jpg)|*.bmp;*.png;*.jpg"</span>
    <span class="highlight-keyword">if</span> fd.ShowDialog()!=System.Windows.Forms.DialogResult.OK:
        <span class="highlight-keyword">return</span> Rhino.Commands.Result.Cancel

    <span class="highlight-comment"># Verify the file that was selected</span>
    image = None
    <span class="highlight-keyword">try</span>:
        image = System.Drawing.Image.FromFile(fd.FileName)
    <span class="highlight-keyword">except</span>:
        <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure

    <span class="highlight-comment"># Allow the user to pick the bitmap origin</span>
    gp = Rhino.Input.Custom.GetPoint()
    gp.SetCommandPrompt(<span class="highlight-literal">"Bitmap Origin"</span>)
    gp.ConstrainToConstructionPlane(True)
    gp.Get()
    <span class="highlight-keyword">if</span> gp.CommandResult()!=Rhino.Commands.Result.Success:
        <span class="highlight-keyword">return</span> gp.CommandResult()

    <span class="highlight-comment"># Get the view that the point was picked in.</span>
    <span class="highlight-comment"># This will be the view that the bitmap appears in.</span>
    view = gp.View()
    <span class="highlight-keyword">if</span> view <span class="highlight-keyword">is</span> None:
        view = scriptcontext.doc.Views.ActiveView
        <span class="highlight-keyword">if</span> view <span class="highlight-keyword">is</span> None: <span class="highlight-keyword">return</span> Rhino.Commands.Result.Failure

    <span class="highlight-comment"># Allow the user to specify the bitmap with in model units</span>
    gn = Rhino.Input.Custom.GetNumber()
    gn.SetCommandPrompt(<span class="highlight-literal">"Bitmap width"</span>)
    gn.SetLowerLimit(<span class="highlight-number">1.0</span>, False)
    gn.Get()
    <span class="highlight-keyword">if</span> gn.CommandResult()!=Rhino.Commands.Result.Success:
        <span class="highlight-keyword">return</span> gn.CommandResult()

    <span class="highlight-comment"># Cook up some scale factors</span>
    w = gn.Number()
    h = w * (image.Width / image.Height)

    plane = view.ActiveViewport.ConstructionPlane()
    plane.Origin = gp.Point()
    view.ActiveViewport.SetTraceImage(fd.FileName, plane, w, h, False, False)
    view.Redraw()
    <span class="highlight-keyword">return</span> Rhino.Commands.Result.Success

<span class="highlight-keyword">if</span> __name__==<span class="highlight-literal">"__main__"</span>:
    AddBackgroundBitmap()</pre></div></div></div><script type="text/javascript">AddLanguageTabSet("ID0EAAABA");</script></div><div class="collapsibleAreaRegion" id="seeAlsoSection"><span class="collapsibleRegionTitle" onclick="SectionExpandCollapse('ID3RB')" onkeypress="SectionExpandCollapse_CheckKey('ID3RB', event)" tabindex="0"><img id="ID3RBToggle" class="collapseToggle" src="../icons/SectionExpanded.png" />See Also</span></div><div id="ID3RBSection" class="collapsibleSection"><h4 class="subHeading">Reference</h4><div class="seeAlsoStyle"><a href="C3F3325A.htm">GetBaseClass Class</a></div><div class="seeAlsoStyle"><a href="185500F3.htm">Rhino.Input.Custom Namespace</a></div></div></div></div><div id="pageFooter" class="pageFooter">Updated 4 October 2015 - Robert McNeel and Associates<p><a href="http://discourse.mcneel.com/" target="_blank">Report wishes and bugs: http://discourse.mcneel.com/</a></p><div class="feedbackLink">Send comments on this topic to
        <a id="HT_MailLink" href="mailto:steve%40mcneel.com?Subject=RhinoCommon SDK">steve@mcneel.com</a></div><script type="text/javascript">
        var HT_mailLink = document.getElementById("HT_MailLink");
        var HT_mailLinkText = HT_mailLink.innerHTML;
        HT_mailLink.href += ": " + document.title + "\u0026body=" + encodeURIComponent("Your feedback is used to improve the documentation and the product. Your e-mail address will not be used for any other purpose and is disposed of after the issue you report is resolved. While working to resolve the issue that you report, you may be contacted via e-mail to get further details or clarification on the feedback you sent. After the issue you report has been addressed, you may receive an e-mail to let you know that your feedback has been addressed.");
        HT_mailLink.innerHTML = HT_mailLinkText;
        </script> </div></body></html>